### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by luebken** [luebken/suasor#32]
And check for example pip install pylint

**Comment by luebken** [comment]
Travis doesn't seem to support pylint at this moment.

**Comment by fridex** [comment]
> Travis doesn't seem to support pylint at this moment.

Take a look at my dispatcher Travis CI configuration at https://github.com/selinon/selinon/blob/master/.travis.yml#L12 I invoke `make check` that runs all the test scenarios and once it succeeds, it runs linters - see [Makefile](https://github.com/selinon/selinon/blob/master/Makefile#L52).  It's really easy to reproduce CI locally - I just run `make check`. To set up development environment (install all dependencies) either in CI or locally I just run `make devenv` and everything is prepared.

**Comment by luebken** [comment]
Setup done: https://github.com/luebken/suasor/tree/travis

But pylint throws an error which I don't know how to fix: 

```
E: 91,42: Module 'numpy' has no 'float64' member (no-member)
``` 
https://travis-ci.org/luebken/suasor/builds/305870646

**Comment by luebken** [comment]
merged. thanks.
